### ISSUE TITLE
【项目推荐】Go-Admin类似PHP的laravel-admin快速开发后台管理

### ISSUE THREAD

**Issue by ziyeziye** [GrowingGit/GitHub-Chinese-Top-Charts#106]
项目地址: https://github.com/GoAdminGroup/go-admin 
中文文档: http://doc.go-admin.cn/zh/ 
分类: Go 

介绍：GoAdmin 类似PHP的laravel-admin，是一个基于 golang 面向生产的数据可视化管理平台搭建框架，可以让你用简短的代码在极短时间内搭建起一个管理后台。

**Comment by ziyeziye** [comment]
项目地址: https://github.com/z-song/laravel-admin
中文文档: https://laravel-admin.org/docs/zh
star:8k+
分类: PHP

项目地址: https://github.com/gogf/gf
中文文档: https://goframe.org/index
star:3k+
分类: GO

**Comment by GrowingGit** [comment]
GoAdminGroup/go-admin：中文总榜 > 软件类 > Go > 31
z-song/laravel-admin：中文总榜 > 软件类 > PHP > 2
gogf/gf：中文总榜 > 软件类 > Go > 25
