### ISSUE TITLE
【项目自荐】算法模板目前1.5k，持续更新中~

### ISSUE THREAD

**Issue by greyireland** [GrowingGit/GitHub-Chinese-Top-Charts#113]
仓库：[greyireland/algorithm-pattern](https://github.com/greyireland/algorithm-pattern)

简介：算法模板，最科学的刷题方式，最快速的刷题路径，你值得拥有~ 🐶

**Comment by kon9chunkit** [comment]
> 仓库：[greyireland/algorithm-pattern](https://github.com/greyireland/algorithm-pattern)
> 
> 简介：算法模板，最科学的刷题方式，最快速的刷题路径，你值得拥有~ 🐶

已收录于Go榜
