### ISSUE TITLE
【项目自荐】web前端（大转盘 / 九宫格）抽奖插件😇

### ISSUE THREAD

**Issue by buuing** [GrowingGit/GitHub-Chinese-Top-Charts#139]
- gtihub：[vue-luck-draw](https://github.com/LuckDraw/vue-luck-draw)
- 文档：[100px.net](https://100px.net?GCTC)

- 描述：🎉一个基于 js / jq / vue / 微信小程序 / uni-app 的【大转盘 / 九宫格】多端适配抽奖插件；🎨奖品 / 文字 / 图片 / 颜色 / 按钮均可配置，支持同步 / 异步抽奖，🏅概率前 / 后端可控，自动根据 dpr 调整清晰度适配移动端

![20201215224305](https://user-images.githubusercontent.com/36689704/102229573-ec423080-3f26-11eb-82c2-32b421c4aedd.png)

**Comment by lizy0329** [comment]
这个真的很棒！

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > TypeScript > 53
