### ISSUE TITLE
【项目自荐】RxHttp 2.5K+ star，持续更新中

### ISSUE THREAD

**Issue by liujingxing** [GrowingGit/GitHub-Chinese-Top-Charts#140]
地址：https://github.com/liujingxing/okhttp-RxHttp

简介：30秒上手，任意请求，仅需3步, 支持Kotlin协程、RxJava2、RxJava3, 已适配Android 10/11 文件上/下载

**Comment by liujingxing** [comment]
自荐项目仅一个月了，为何还不在java榜上？

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > Kotlin > 9
