### ISSUE TITLE
【项目自荐】Android广告聚合项目，助力开发者收入增长

### ISSUE THREAD

**Issue by ifmvo** [GrowingGit/GitHub-Chinese-Top-Charts#149]
https://github.com/ifmvo/TogetherAd
🔥持续更新。Android广告聚合：帮助 Android 开发者快速、便捷、灵活的接入国内多家主流安卓广告 SDK。广点通（优量汇）、穿山甲、百青藤（百度Mob）。开屏广告、Banner横幅广告、插屏广告、激励广告、原生信息流、全屏广告。

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > Kotlin > 63
