### ISSUE TITLE
【项目自荐】一个比libevent、libuv更易用的国产c/c++网络库libhv

### ISSUE THREAD

**Issue by ithewei** [GrowingGit/GitHub-Chinese-Top-Charts#156]
- 项目地址：https://github.com/ithewei/libhv.git
- star数：>2k
- 中文README：https://github.com/ithewei/libhv/blob/master/README-CN.md
- 中文教程：https://hewei.blog.csdn.net/article/details/113733758

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > C > 32
