### ISSUE TITLE
【自荐】Hutool 一个小而全的Java工具类库

### ISSUE THREAD

**Issue by looly** [GrowingGit/GitHub-Chinese-Top-Charts#181]
![image](https://user-images.githubusercontent.com/1432613/125115300-bc09eb80-e11d-11eb-945f-336bd9091c41.png)

地址：https://github.com/dromara/hutool
类别：Java
star数：19K
介绍：Hutool是一个小而全的Java工具类库，通过静态方法封装，降低相关API的学习成本，提高工作效率，使Java拥有函数式语言般的优雅，让Java语言也可以“甜甜的”。

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > Java > 16

**Comment by looly** [comment]
十分感谢~~
