### ISSUE TITLE
L0CV - 一种结合了代码、图示和HTML的在线学习媒介

### ISSUE THREAD

**Issue by Charmve** [GrowingGit/GitHub-Chinese-Top-Charts#196]
本学习资源以计算机视觉的发展历程和自顶向下的学习过程为核心，为读者提供一个 人人可学习计算机视觉的开放平台。我们围绕这样的组织逻辑：什么是计算机视觉？计算机视觉解决什么问题，都是怎么解决的？传统方法——以卷积神经网络为中心的神经网络；现代方法——Transformer、强化学习、迁移学习、生成对抗等。各种方法是如何实现的，用到了什么框架？在本资源中，这些问题都将会给予解决。

![image](https://user-images.githubusercontent.com/29084184/127259248-067fa4ac-7342-4ed1-90d0-b94b797749c3.png)

- 项目主页 https://charmve.github.io/L0CV-web/
- 在线电子书 https://charmve.github.io/computer-vision-in-action
- GitHub 源代码/Notebook https://github.com/Charmve/computer-vision-in-action

<br>

![image](https://user-images.githubusercontent.com/29084184/127259438-93885219-8d96-493e-a9e6-ea6605043106.png)

![image](https://user-images.githubusercontent.com/29084184/127259422-5f674f91-c66f-404e-b261-e21cf7ef0e2f.png)

**Comment by GrowingGit** [comment]
中文总榜 > 资料类 > Jupyter Notebook > 25
