### ISSUE TITLE
【项目推荐】深度学习OCR领域TOP1&预训练模型应用工具TOP1

### ISSUE THREAD

**Issue by grasswolfs** [GrowingGit/GitHub-Chinese-Top-Charts#205]
中文深度学习OCR领域TOP1  PaddleOCR  目前trending 全球榜单第4，star14.5k https://github.com/PaddlePaddle/PaddleOCR
中文预训练模型应用工具TOP1 PaddleHub 包含预训练模型超过300个，star 6.9k https://github.com/PaddlePaddle/PaddleHub

![trending TOP4-20210813](https://user-images.githubusercontent.com/23690325/129351966-f0fa5ad9-d0d1-499c-994b-602fbcc1eee7.png)

**Comment by GrowingGit** [comment]
PaddlePaddle/PaddleOCR：中文总榜 > 软件类 > Python > 9
PaddlePaddle/PaddleHub：中文总榜 > 软件类 > Python > 33
