### ISSUE TITLE
【PHP】添加 Laravel Swoole 适配器 - LaravelS

### ISSUE THREAD

**Issue by hhxsv5** [GrowingGit/GitHub-Chinese-Top-Charts#208]
[LaravelS](https://github.com/hhxsv5/laravel-s) 是 Swoole 和 Laravel/Lumen 之间开箱即用的适配器。
[中文文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md)。

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > PHP > 18
