### ISSUE TITLE
【项目推荐】C#的ABP框架

### ISSUE THREAD

**Issue by afresh** [GrowingGit/GitHub-Chinese-Top-Charts#231]
项目简介：ABP是用于创建现代Web应用程序的完整架构和强大的基础设施！遵循最佳实践和约定，为你提供SOLID开发经验。
官网：[https://abp.io/](https://abp.io/)
源码：[https://github.com/abpframework/abp](https://github.com/abpframework/abp) Fork: 2.3k, Star: 7.3k.

**Comment by winray** [comment]
我已收到，我会尽快给您回复。

**Comment by zhihui1999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
已经收到邮件，看到后尽快回复的

**Comment by ousiwwi** [comment]
您发给我的邮件已经收到，感谢您的支持！
