### ISSUE TITLE
【开源自荐】 PrimiHub - 开源隐私计算平台

### ISSUE THREAD

**Issue by LinuxSuRen** [GrowingGit/GitHub-Chinese-Top-Charts#267]
- 项目名称：PrimiHub

- 项目地址：https://github.com/primihub/primihub

- 项目简介 (**100** 字以内)：PrimiHub 从密码学等底层技术确保了数据在计算过程中不回被泄漏，支持多方计算、联邦学习、隐私求交(PSI)、隐私查询(PIR)等特性，支持数据源接入、数据消费、接入应用、语法、语义、安全协议多方面的扩展。

- 项目截图 (**6**张以内)：

![image](https://user-images.githubusercontent.com/1450685/201810083-a2a8483e-9c6b-49a3-828a-2115a1a5586e.png)

![image](https://user-images.githubusercontent.com/1450685/201810110-a9e8c37d-fafe-46ba-9eb6-d696488840e6.png)

**Comment by winray** [comment]
我已收到，我会尽快给您回复。

**Comment by 82940854** [comment]
您的邮件已收到，我将尽快给您答复。

**Comment by zhihui1999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
已经收到邮件，看到后尽快回复的

**Comment by hg612** [comment]
谢谢来信

**Comment by SparkHan** [comment]
我现在不在，如果有事请用QQ找我。

**Comment by ousiwwi** [comment]
您发给我的邮件已经收到，感谢您的支持！
