### ISSUE TITLE
自荐项目SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER

### ISSUE THREAD

**Issue by JACK-THINK** [GrowingGit/GitHub-Chinese-Top-Charts#32]
自荐项目[SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER)，Shell语言，全部代码配有中/英文对照注释，注释粒度基本到逐条语句

**Comment by kon9chunkit** [comment]
项目的 Description 也要有中文说明才可以收录的

**Comment by JACK-THINK** [comment]
@kon9chunkit 
已添加中文Description

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > Shell > 117
