### ISSUE TITLE
您好，能否考察下TqSdk，国内量化历史行情数据交易通道完全免费的Python开发包

### ISSUE THREAD

**Issue by shinny-xuyida** [GrowingGit/GitHub-Chinese-Top-Charts#36]
TqSdk 提供的功能可以支持从简单到复杂的各类策略程序.

用户无需向期货公司申请AppId, 即可满足穿透式监管信息采集规范要求
公司级数据运维，提供当前所有可交易合约从上市开始的 全部Tick数据和K线数据
支持市场上90%的期货公司 实盘交易
支持 模拟交易
支持 Tick级和K线级回测, 支持 复杂策略回测
提供近百个 技术指标函数及源码
用户无须建立和维护数据库, 行情和交易数据全在 内存数据库 , 无访问延迟
优化支持 pandas 和 numpy 库
无强制框架结构, 支持任意复杂度的策略, 在一个交易策略程序中使用多个品种的K线/实时行情并交易多个品种
配合开发者支持工具，能够进行交易信号打点，支持自定义指标画图

**Comment by kon9chunkit** [comment]
@Qweringo 有收录，Python榜#122
