### ISSUE TITLE
vue 排行榜自己提名一下哈哈

### ISSUE THREAD

**Issue by x-cold** [GrowingGit/GitHub-Chinese-Top-Charts#45]
https://github.com/N3-components/N3-components
N3组件库是基于Vue.js构建的，让前端工程师和全栈工程师能快速构建页面和应用。

https://github.com/N3-components/N3-admin
本项目基于N3-components提供基本组件，是入门vue全家桶较全面的demo，同时也是一套可扩展的Admin模板。N3-admin适用于单页应用的快速上手，并不仅限于N3-components的使用，而是提供一个比较完善的项目构建的思路和结构，提供给初学者学习。

**Comment by kon9chunkit** [comment]
项目 Description 也要有中文说明才可以收录的

**Comment by x-cold** [comment]
有的 切换成中文就有啦
