### ISSUE TITLE
8.5k star 的vue项目自荐

### ISSUE THREAD

**Issue by lin-xin** [GrowingGit/GitHub-Chinese-Top-Charts#46]
https://github.com/lin-xin/vue-manage-system
基于vue + element的后台管理系统解决方案，更新活跃

**Comment by kon9chunkit** [comment]
已收录

**Comment by kon9chunkit** [comment]
> https://github.com/lin-xin/vue-manage-system
> 基于vue + element的后台管理系统解决方案，更新活跃

已收录
