### ISSUE TITLE
gochat - 纯go实现的im即时通讯系统 goim 🚀🚀🚀🚀🚀

### ISSUE THREAD

**Issue by LockGit** [GrowingGit/GitHub-Chinese-Top-Charts#53]
## 项目推荐
- 🚀 项目地址：
https://github.com/LockGit/gochat

- 类别：Go

- 项目描述：
```
gochat为纯go实现的即时通讯系统,支持私信消息与房间广播消息,各层之间通过rpc通讯,支持水平扩展。
使用redis作为消息存储与投递的载体,相对kafka操作起来更加方便快捷,所以十分轻量。
各层之间基于etcd服务发现,在扩容部署时将会方便很多。
由于go的交叉编译特性,编译后可以快速在各个平台上运行,gochat架构及目录结构清晰,
并且本项目还贴心的提供了docker一键构建所有环境依赖,安装起来十分便捷。
```

- 推荐理由：
```
轻量快捷不臃肿,水平可扩展,docker快速构建所有环境,迅速体验im即时通讯,
各层架构清晰,文档说明详细。
```

截图：
系统架构：
 ![](https://github.com/LockGit/gochat/raw/master/architecture/gochat.png)

服务发现：
![](https://github.com/LockGit/gochat/raw/master/architecture/gochat_discovery.png)

消息投递 
![](https://github.com/LockGit/gochat/raw/master/architecture/single_send.png)

聊天室预览:
![](https://github.com/LockGit/gochat/raw/master/architecture/gochat.gif)

**Comment by kon9chunkit** [comment]
项目description加上中文描述即可收录

**Comment by LockGit** [comment]
@kon9chunkit 这个默认就是中文readme描述

**Comment by kon9chunkit** [comment]
> @kon9chunkit 这个默认就是中文readme描述

除了readme，标题下面的描述也要包含中文描述的

**Comment by LockGit** [comment]
加了4个字中文，但是我还是认为这种模式不太好，我觉得readme提供了中文就可以了，如果这个都不能看懂就没有学习的必要了

**Comment by kon9chunkit** [comment]
> 加了4个字中文，但是我还是认为这种模式不太好，我觉得readme提供了中文就可以了，如果这个都不能看懂就没有学习的必要了

已收录于Go榜
