### ISSUE TITLE
【项目推荐】 Day.js 替换 moment.js 的轻量级 JavaScript 时间日期处理库

### ISSUE THREAD

**Issue by ghost** [GrowingGit/GitHub-Chinese-Top-Charts#62]
项目地址：https://github.com/iamkun/dayjs

项目简介： Day.js 是一个仅 2kb 大小的轻量级 JavaScript 时间日期处理库，和 Moment.js 的 API 设计保持完全一样。如果你曾经用过 Moment.js ，那么你已经知道如何使用 Day.js 。

推荐理由： 2万星星 国人开源库 非常好用 作者 @iamkun 还是 element UI 的开发成员

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > JavaScript > 6
