### ISSUE TITLE
【自荐项目】链家房源爬虫

### ISSUE THREAD

**Issue by XuefengHuang** [GrowingGit/GitHub-Chinese-Top-Charts#63]
项目推荐
项目地址：https://github.com/XuefengHuang/lianjia-scrawler

类别：Python

项目描述：
该项目提供一个链家网全国房源爬虫工具，数据存储目前支持Mysql,Sqlite和Postgres。非常方便转化成csv等格式文件。

star数：2.1K

**Comment by kon9chunkit** [comment]
已收录于Python榜
