### ISSUE TITLE
【项目推荐】C++ 编写的分布式图数据库

### ISSUE THREAD

**Issue by nebula-package** [GrowingGit/GitHub-Chinese-Top-Charts#64]
- 项目地址：https://github.com/vesoft-inc/nebula

- 使用语言：C++

- 目前 Star 数：1878（截止时间为 2020.01.15 15:00）

- 项目简介： Nebula Graph 是一款开源的图数据库，擅长处理千亿个顶点和万亿条边的超大规模数据集。与其他图数据库产品相比，Nebula Graph 具有如下优势：
    - 全对称分布式架构
    - 存储与计算分离
    - 水平可扩展性
    - RAFT 协议下的数据强一致
    - 类 SQL 查询语言
    - 用户鉴权

**Comment by kon9chunkit** [comment]
项目description加上中文描述即可收录

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > C++ > 20
