### ISSUE TITLE
【项目自荐】shell LNMP一键安装脚本

### ISSUE THREAD

**Issue by licess** [GrowingGit/GitHub-Chinese-Top-Charts#84]
https://github.com/licess/lnmp 一个shell脚本写的lnmp/lnmpa/lamp环境部署工具，更新算比较频繁，目前1.6k star
谢谢。

**Comment by kon9chunkit** [comment]
项目description加上中文描述即可收录

**Comment by licess** [comment]
已经更新description

**Comment by kon9chunkit** [comment]
> 已经更新description

已收录于Shell榜

**Comment by licess** [comment]
好像没有

**Comment by GrowingGit** [comment]
中文总榜 > 软件类 > Shell > 23
