### ISSUE TITLE
【推荐项目】Python开源运维平台

### ISSUE THREAD

**Issue by zyupo** [GrowingGit/GitHub-Chinese-Top-Charts#97]
开源运维平台：面向中小型企业设计的无 Agent的自动化运维平台，包含主机管理、主机批量执行、主机在线终端、应用发布、任务计划、配置中心、监控、报警等一系列功能。

项目地址：https://github.com/openspug/spug

**Comment by kon9chunkit** [comment]
> 开源运维平台：面向中小型企业设计的无 Agent的自动化运维平台，包含主机管理、主机批量执行、主机在线终端、应用发布、任务计划、配置中心、监控、报警等一系列功能。
> 
> 项目地址：https://github.com/openspug/spug

已收录的
